global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "face_api"
    static_configs:
      - targets: ["face-api:8000"] # TÃªn service trong docker-compose
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
